# Generated by Django 2.1.7 on 2019-02-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='last_name',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
